package ru.stqa.pft.addressbook;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Test;

public class GroupDeletionTests extends TestBase {

  @Test
  public void testGroupDelition() {
    gotoGroupPage();
    selectGroup();
    deleteSelectedGroups();
    returnToGroupPage();
  }

  @After
  public void tearDown() {
    driver.quit();
  }
}
