package ru.stqa.pft.addressbook;// Generated by Selenium IDE

import org.junit.Test;

public class GroupCreationTests extends TestBase {

  @Test
  public void testGroupCreation() {
    returnToGroupPage();
    initGroupCreation();
    fillGroupForm(new GroupData("test1", "test2", "test3"));
    submitGroupCreation();
    returnToGroupPage();
  }

}
