package tests;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Test;

public class GroupDeletionTests extends TestBase {

  @Test
  public void testGroupDeletion() {
    app.returnToGroupPage();
    app.selectGroup();
    app.deleteSelectedGroups();
    app.returnToGroupPage();
  }

  @After
  public void tearDown() {
    app.stop();
  }
}
